# Generated by Django 4.2.7 on 2024-01-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_category_books_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
    ]
