# Generated by Django 4.2.7 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
