# Generated by Django 4.2.7 on 2024-01-09 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0002_alter_borrow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='user',
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
